jobs:
  build:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Compile and Build OpenAPI file
      run: ./mvnw compile
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Update Documentation
      run: 'cp -r api-doc/target/openapi/signal-server-openapi.yaml /tmp/

        git config user.email "github@signal.org"

        git config user.name "Documentation Updater"

        git fetch origin gh-pages

        git checkout gh-pages

        cp /tmp/signal-server-openapi.yaml .

        git diff --quiet || git commit -a -m "Updating documentation"

        git push origin gh-pages -q

        '
name: Update Documentation
on:
  repository_dispatch:
    types: trigger-ga___documentation.yml
