jobs:
  build:
    if: ${{ vars.INTEGRATION_TESTS_BUCKET != '' }}
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ROLE }}
    - continue-on-error: true
      name: Fetch integration utils library
      run: 'mkdir -p integration-tests/.libs

        mkdir -p integration-tests/src/main/resources

        wget -O integration-tests/.libs/software.amazon.awssdk-sso.jar https://repo1.maven.org/maven2/software/amazon/awssdk/sso/2.19.8/sso-2.19.8.jar

        aws s3 cp "s3://${{ vars.INTEGRATION_TESTS_BUCKET }}/config-latest.yml" integration-tests/src/main/resources/config.yml

        '
    - continue-on-error: true
      name: Run and verify integration tests
      run: ./mvnw clean compile test-compile failsafe:integration-test failsafe:verify
name: Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___integration-tests.yml
